//! PAM authentication and session management.
//!
//! FFI bindings are generated by bindgen from `src/pam_appl.h` (which is the
//! actual Linux-PAM application header). The `ffi` module re-exports everything
//! generated into `$OUT_DIR/pam_appl.rs`.
//!
//! Lifecycle performed by [`PamSession::open`]:
//!   `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
//!   `pam_setcred(ESTABLISH)` → `pam_open_session`
//!
//! [`Drop`] runs:
//!   `pam_close_session` → `pam_setcred(DELETE)` → `pam_end`
//!

// pam_limits    | Applies resource limits (ulimits) from /etc/security/limits.conf
// pam_mkhomedir | Creates home directory on first login if it doesn't exist
// pam_unix      | Core Unix auth — checks passwords against /etc/shadow
// pam_localuser | Succeeds only if user exists in local /etc/passwd
// pam_exec      | Runs an arbitrary external command during auth


#![allow(non_upper_case_globals)]

use std::ffi::*;
use std::net::SocketAddr;
use std::ptr;

mod ffi {
    #![allow(unused)]
    #![allow(non_camel_case_types)]

    include!(concat!(env!("OUT_DIR"), "/pam_appl.rs"));
}

/// An open PAM session for an authenticated user.
///
/// Created via [`PamSession::open`]. Dropping this value closes the session
/// and ends the PAM transaction.
pub struct Session {
    handle: *mut ffi::pam_handle_t,
    status: u32,
}

// SAFETY: the PAM handle is owned exclusively by this struct; we never share
// it across threads and all access is through exclusive ownership.
unsafe impl Send for Session {}

macro_rules! pam {
    ($self:expr, $fn:expr, $($param:expr),* $(,)?) => {{
        let res = $fn($self.handle, $($param),*);
        $self.result(stringify!($fn), res)
    }}
}

impl Session {
    fn null(username: &str, password: &str) -> anyhow::Result<Self> {
        Ok(Self {
            handle: std::ptr::null_mut(),
            status: ffi::PAM_SUCCESS,
        })
    }

    fn status_str(&self) -> &'static str {
        // SAFETY: todo
        let ptr = unsafe { ffi::pam_strerror(self.handle, self.status.cast_signed()) };
        if ptr.is_null() {
            return "* null *";
        }
        // SAFETY: if the pointer returned by pam_strerror is not null then it's
        // guaranteed to point to a null-terminated byte string
        let str = unsafe { CStr::from_ptr(ptr) };

        str.to_str().unwrap_or("* invalid *")
    }

    fn result(&mut self, step: &str, result: c_int) -> anyhow::Result<()> {
        self.status = result.cast_unsigned();
        anyhow::ensure!(self.status == ffi::PAM_SUCCESS, self.status_str());
        Ok(())
    }

    /// Starts a PAM session with the "ssh-server" service
    fn start(&mut self) -> anyhow::Result<()> {
        // SAFETY:
        // - `service_name` is a null-terminated byte string
        // - `username` is a null-terminated byte string
        let res = unsafe {
            ffi::pam_start(
                c"ssh-server".as_ptr(),
                ptr::null(),
                ptr::null(),
                &mut self.handle,
            )
        };
        self.result("ffi::pam_start", res)
    }

    /// Sets a PAM item that is expected to be a C string.
    ///
    /// # Safety
    ///
    /// The selected `item` must be one that Linux-PAM expects to be a C string (e.g. `PAM_AUTHTOK` or `PAM_RHOST`).
    unsafe fn set_cstr_item(&mut self, item: u32, value: impl Into<Vec<u8>>) -> anyhow::Result<()> {
        let str = CString::new(value)?;
        // SAFETY: todo
        unsafe {
            pam!(
                self,
                ffi::pam_set_item,
                item.cast_signed(),
                str.as_ptr() as *const _
            )
        }
    }

    /// Authenticate `username`/`password` against the `"ssh-server"` PAM service
    /// and open a session.
    ///
    /// Runs `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
    /// `pam_setcred(ESTABLISH)` → `pam_open_session`.
    /// Dropping the returned value closes the session via `pam_close_session`,
    /// `pam_setcred(DELETE)`, and `pam_end`.
    pub fn open(username: &str, password: &str, /* host: SocketAddr */) -> anyhow::Result<Self> {
        let mut session = Self::null(username, password)?;
        session.start()?;
        unsafe extern "C" fn nodelay(_: c_int, _: c_uint, _: *const c_void) {}
        // SAFETY: todo
        unsafe {
            pam!(
                session,
                ffi::pam_set_item,
                ffi::PAM_FAIL_DELAY.cast_signed(),
                nodelay as *const _
            )
        }?;
        // SAFETY: todo
        unsafe { session.set_cstr_item(ffi::PAM_AUTHTOK, password) }?;
        // SAFETY: todo
        unsafe { session.set_cstr_item(ffi::PAM_RUSER, username) }?;
        // // SAFETY: todo
        // unsafe { session.set_cstr_item(ffi::PAM_RHOST, host.to_string()) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_authenticate, 0) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_acct_mgmt, 0) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_setcred, ffi::PAM_ESTABLISH_CRED as c_int) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_open_session, 0) }?;
        Ok(session)
    }
}

impl Drop for Session {
    fn drop(&mut self) {
        if self.handle.is_null() {
            return;
        }
        // SAFETY: handle is valid and we have exclusive ownership.
        unsafe {
            ffi::pam_close_session(self.handle, 0);
            ffi::pam_setcred(self.handle, ffi::PAM_DELETE_CRED as c_int);
            ffi::pam_end(self.handle, self.status.cast_signed());
        }
        self.handle = ptr::null_mut();
    }
}
