//! PAM authentication and session management.
//!
//! FFI bindings are generated by bindgen from `src/pam_appl.h` (which is the
//! actual Linux-PAM application header). The `ffi` module re-exports everything
//! generated into `$OUT_DIR/pam_appl.rs`.
//!
//! Lifecycle performed by [`PamSession::open`]:
//!   `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
//!   `pam_setcred(ESTABLISH)` → `pam_open_session` → `pam_setcred(REINITIALIZE)`
//!
//! [`Drop`] runs:
//!   `pam_close_session` → `pam_setcred(DELETE)` → `pam_end`

#![allow(non_upper_case_globals)]

use std::ffi::{CStr, CString};
use std::mem::{MaybeUninit, size_of};
use std::os::raw::{c_int, c_void};
use std::ptr::{self, NonNull};

mod ffi {
    #![allow(unused)]
    #![allow(non_camel_case_types)]

    include!(concat!(env!("OUT_DIR"), "/pam_appl.rs"));
}

// ── Conversation callback ─────────────────────────────────────────────────────

struct Credentials {
    username: CString,
    password: CString,
}

/// PAM conversation function.
///
/// Responds with the password for `PAM_PROMPT_ECHO_OFF` prompts and the
/// username for `PAM_PROMPT_ECHO_ON` prompts.
///
/// Response buffer and strings are allocated with `libc::malloc` so that the PAM
/// library can `free()` them with its own allocator.
unsafe extern "C" fn conversation(
    num_msg: c_int,
    msg: *mut *const ffi::pam_message,
    resp: *mut *mut ffi::pam_response,
    appdata_ptr: *mut c_void,
) -> c_int {
    let Ok(num_msg) = num_msg.try_into() else {
        return ffi::PAM_CONV_ERR as c_int;
    };

    // SAFETY: this function is only called in `PamSession::authenticate` which always
    // sets the `appdata_ptr` to a pointer to a value of type `Credentials`
    let creds = unsafe { &*appdata_ptr.cast::<Credentials>() };

    // SAFETY: in theory in `msg` we have exclusive access to an array
    // of references to initialized `pam_message` items
    let msg = unsafe { std::slice::from_raw_parts_mut(msg as *mut &ffi::pam_message, num_msg) };

    // SAFETY: todo
    let Some(responses) = unsafe { malloc::<ffi::pam_response>(num_msg) } else {
        return ffi::PAM_BUF_ERR.cast_signed();
    };

    for (r, m) in responses.iter_mut().zip(msg) {
        let resp = match m.msg_style.cast_unsigned() {
            ffi::PAM_PROMPT_ECHO_OFF => unsafe { malloc_cstr(&creds.password) }.map(|s| s.as_mut_ptr()),
            ffi::PAM_PROMPT_ECHO_ON => unsafe { malloc_cstr(&creds.username) }.map(|s| s.as_mut_ptr()),
            _ => Some(std::ptr::null_mut()),
        };
        let Some(resp) = resp else { return ffi::PAM_BUF_ERR.cast_signed() };
        r.write(ffi::pam_response {
            resp,
            resp_retcode: 0,
        });
    }
    // SAFETY: the PAM library guarantees that resp is a pointer to a pam_response
    unsafe { *resp = responses.as_mut_ptr() as *mut _ };
    ffi::PAM_SUCCESS as c_int
}

// ── PamSession ────────────────────────────────────────────────────────────────

/// An open PAM session for an authenticated user.
///
/// Created via [`PamSession::open`]. Dropping this value closes the session
/// and ends the PAM transaction.
pub struct PamSession {
    handle: *mut ffi::pam_handle_t,
    status: u32,
    // Both fields below must outlive `handle`: Linux-PAM stores a pointer to
    // `conv` internally, and `conv.appdata_ptr` points into `creds`.
    conv: Box<ffi::pam_conv>,
    creds: Box<Credentials>,
}

// SAFETY: the PAM handle is owned exclusively by this struct; we never share
// it across threads and all access is through exclusive ownership.
unsafe impl Send for PamSession {}

impl PamSession {
    fn null(username: &str, password: &str) -> anyhow::Result<Self> {
        let creds = Box::new(Credentials {
            username: CString::new(username)?,
            password: CString::new(password)?,
        });

        let conv = Box::new(ffi::pam_conv {
            conv: Some(conversation),
            appdata_ptr: &*creds as *const Credentials as *mut c_void,
        });

        Ok(Self {
            handle: std::ptr::null_mut(),
            status: ffi::PAM_SUCCESS,
            conv,
            creds,
        })
    }

    fn status_str(&self) -> &'static str {
        // SAFETY: todo
        let ptr = unsafe { ffi::pam_strerror(self.handle, self.status.cast_signed()) };
        if ptr.is_null() {
            return "* null *";
        }
        // SAFETY: if the pointer returned by pam_strerror is not null then it's
        // guaranteed to point to a null-terminated byte string
        let str = unsafe { CStr::from_ptr(ptr) };

        str.to_str().unwrap_or("* invalid *")
    }

    fn result(&mut self, result: c_int) -> anyhow::Result<&mut Self> {
        self.status = result.cast_unsigned();
        anyhow::ensure!(self.status == ffi::PAM_SUCCESS, self.status_str());
        Ok(self)
    }

    fn start(&mut self) -> anyhow::Result<&mut Self> {
        // SAFETY: todo
        let res = unsafe {
            ffi::pam_start(
                c"ssh-server".as_ptr(),
                self.creds.username.as_ptr(),
                &*self.conv,
                &mut self.handle,
            )
        };
        self.result(res)
    }

    fn authenticate_(&mut self) -> anyhow::Result<&mut Self> {
        // SAFETY: todo
        self.result(unsafe { ffi::pam_authenticate(self.handle, 0) })
    }

    fn acct_mgmt(&mut self) -> anyhow::Result<&mut Self> {
        // SAFETY: todo
        self.result(unsafe { ffi::pam_acct_mgmt(self.handle, 0) })
    }

    fn setcred(&mut self) -> anyhow::Result<&mut Self> {
        // SAFETY: todo
        self.result(unsafe { ffi::pam_setcred(self.handle, ffi::PAM_ESTABLISH_CRED as c_int) })
    }

    fn end(&mut self) -> anyhow::Result<&mut Self> {
        // SAFETY: todo
        self.result(unsafe { ffi::pam_end(self.handle, 0) })
    }

    /// Authenticate `username`/`password` against the `"ssh-server"` PAM service.
    ///
    /// Runs `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
    /// `pam_setcred(ESTABLISH)` in the **parent** process. The session is not
    /// opened here; call [`child_setup`] and pass its result to
    /// `Command::pre_exec` so that `pam_open_session` runs in the child
    /// process (after fork, before exec), tying resource limits and accounting
    /// to the shell's lifetime.
    pub fn authenticate(username: &str, password: &str) -> anyhow::Result<Self> {
        let mut handle = Self::null(username, password)?;
        handle.start()?.authenticate_()?.acct_mgmt()?.setcred()?;
        Ok(handle)
    }

    /// Returns a closure intended for use with `Command::pre_exec`.
    ///
    /// The closure runs in the **child** process after `fork` and before
    /// `exec`. It calls `pam_open_session` (which applies resource limits via
    /// `pam_limits`, writes utmp/wtmp login records, etc.) and then
    /// `pam_setcred(REINITIALIZE)`, both of which must take effect in the
    /// child so that the shell inherits them.
    ///
    /// `pam_close_session` is called from the parent when [`PamSession`] is
    /// dropped (i.e. when the SSH connection ends), writing the logout record.
    pub fn child_setup(&self) -> impl FnMut() -> std::io::Result<()> + Send + 'static {
        // Cast to usize so the closure is `Send` — usize is always Send.
        // The address remains valid in the child because fork copies the entire
        // parent address space; the pointer is used before exec replaces it.
        let handle = self.handle as usize;
        move || {
            let handle = handle as *mut ffi::pam_handle_t;
            let rc = unsafe { ffi::pam_open_session(handle, 0) };
            if rc != ffi::PAM_SUCCESS as c_int {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::PermissionDenied,
                    format!("pam_open_session failed (PAM error code {rc})"),
                ));
            }
            unsafe { ffi::pam_setcred(handle, ffi::PAM_REINITIALIZE_CRED as c_int) };
            Ok(())
        }
    }
}

impl Drop for PamSession {
    fn drop(&mut self) {
        if self.handle.is_null() {
            return;
        }
        // SAFETY: handle is valid and we have exclusive ownership.
        unsafe {
            ffi::pam_close_session(self.handle, 0);
            ffi::pam_setcred(self.handle, ffi::PAM_DELETE_CRED as c_int);
            ffi::pam_end(self.handle, self.status.cast_signed());
        }
        self.handle = ptr::null_mut();
    }
}

/// Utility function to allocate a slice with [`libc::malloc`]
///
/// # Safety
///
/// Same as [`libc::malloc`]
unsafe fn malloc<T>(len: usize) -> Option<&'static mut [MaybeUninit<T>]> {
    let size = len * size_of::<T>();
    // SAFETY: caller must ensure the safety requirements of malloc
    let ptr = unsafe { libc::malloc(size) };
    let ptr = NonNull::new(ptr as *mut MaybeUninit<T>)?;
    // SAFETY: given that the pointer is not null, malloc didn't fail and thus
    // we have gained exclusive access to an unitialized slice of len T items
    Some(unsafe { std::slice::from_raw_parts_mut(ptr.as_ptr(), len) })
}

/// Utility function to allocate a C null-terminated string with [`libc::malloc`]
///
/// # Safety
///
/// Same as [`libc::malloc`]
unsafe fn malloc_cstr(str: &CStr) -> Option<&'static mut [i8]> {
    fn cast(i: &[u8]) -> &[i8] {
        // SAFETY: u8 and i8 have the same binary representation
        unsafe { std::slice::from_raw_parts(i.as_ptr() as *const _, i.len()) }
    }
    let str = cast(str.to_bytes_with_nul());
    // SAFETY: caller must ensure the safety requirements of malloc
    let slice = unsafe { malloc(str.len()) }?;
    Some(slice.write_copy_of_slice(str))
}
