//! PAM authentication and session management.
//!
//! FFI bindings are generated by bindgen from `src/pam_appl.h` (which is the
//! actual Linux-PAM application header). The `ffi` module re-exports everything
//! generated into `$OUT_DIR/pam_appl.rs`.
//!
//! Lifecycle performed by [`PamSession::open`]:
//!   `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
//!   `pam_setcred(ESTABLISH)` → `pam_open_session` → `pam_setcred(REINITIALIZE)`
//!
//! [`Drop`] runs:
//!   `pam_close_session` → `pam_setcred(DELETE)` → `pam_end`

#![allow(non_upper_case_globals)]

use std::ffi::CString;
use std::os::raw::{c_int, c_void};
use std::ptr;

mod ffi {
    #![allow(unused)]
    #![allow(non_camel_case_types)]

    include!(concat!(env!("OUT_DIR"), "/pam_appl.rs"));
}

// ── Conversation callback ─────────────────────────────────────────────────────

struct Credentials {
    username: CString,
    password: CString,
}

/// PAM conversation function.
///
/// Responds with the password for `PAM_PROMPT_ECHO_OFF` prompts and the
/// username for `PAM_PROMPT_ECHO_ON` prompts.
///
/// Response strings are allocated with `libc::strdup` so that the PAM library
/// can `free()` them with its own allocator. The response array itself is
/// allocated with `libc::malloc` for the same reason.
unsafe extern "C" fn conversation(
    num_msg: c_int,
    msg: *mut *const ffi::pam_message,
    resp: *mut *mut ffi::pam_response,
    appdata_ptr: *mut c_void,
) -> c_int {
    unsafe {
        let creds = &*(appdata_ptr as *const Credentials);

        let responses = libc::malloc(num_msg as usize * std::mem::size_of::<ffi::pam_response>())
            as *mut ffi::pam_response;
        if responses.is_null() {
            return ffi::PAM_BUF_ERR as c_int;
        }

        for i in 0..num_msg as usize {
            let m = &**msg.add(i);
            let r = &mut *responses.add(i);
            r.resp_retcode = 0;
            r.resp = match m.msg_style {
                s if s == ffi::PAM_PROMPT_ECHO_OFF as c_int => libc::strdup(creds.password.as_ptr()),
                s if s == ffi::PAM_PROMPT_ECHO_ON as c_int => libc::strdup(creds.username.as_ptr()),
                _ => ptr::null_mut(),
            };
        }

        *resp = responses;
        ffi::PAM_SUCCESS as c_int
    }
}

// ── PamSession ────────────────────────────────────────────────────────────────

/// An open PAM session for an authenticated user.
///
/// Created via [`PamSession::open`]. Dropping this value closes the session
/// and ends the PAM transaction.
pub struct PamSession {
    handle: *mut ffi::pam_handle_t,
    last_status: c_int,
    // Both fields below must outlive `handle`: Linux-PAM stores a pointer to
    // `_conv` internally, and `_conv.appdata_ptr` points into `_creds`.
    _conv: Box<ffi::pam_conv>,
    _creds: Box<Credentials>,
}

// SAFETY: the PAM handle is owned exclusively by this struct; we never share
// it across threads and all access is through exclusive ownership.
unsafe impl Send for PamSession {}

impl PamSession {
    /// Authenticate `username`/`password` against the `"sshd"` PAM service
    /// and open a session.
    pub fn open(username: &str, password: &str) -> anyhow::Result<Self> {
        let service = CString::new("sshd")?;
        let user = CString::new(username)?;

        let creds = Box::new(Credentials {
            username: CString::new(username)?,
            password: CString::new(password)?,
        });

        // `conv.appdata_ptr` points into `creds`; both are moved into the
        // returned `PamSession` so they stay alive for the duration.
        let conv = Box::new(ffi::pam_conv {
            conv: Some(conversation),
            appdata_ptr: &*creds as *const Credentials as *mut c_void,
        });

        let mut handle: *mut ffi::pam_handle_t = ptr::null_mut();

        macro_rules! pam {
            ($call:expr, $msg:literal) => {{
                let rc = unsafe { $call };
                if rc != ffi::PAM_SUCCESS as c_int {
                    anyhow::bail!(concat!($msg, " failed (PAM error code {})"), rc);
                }
            }};
        }

        pam!(ffi::pam_start(service.as_ptr(), user.as_ptr(), &*conv, &mut handle), "pam_start");
        pam!(ffi::pam_authenticate(handle, 0), "pam_authenticate");
        pam!(ffi::pam_acct_mgmt(handle, 0), "pam_acct_mgmt");
        pam!(ffi::pam_setcred(handle, ffi::PAM_ESTABLISH_CRED as c_int), "pam_setcred(establish)");
        pam!(ffi::pam_open_session(handle, 0), "pam_open_session");
        pam!(ffi::pam_setcred(handle, ffi::PAM_REINITIALIZE_CRED as c_int), "pam_setcred(reinitialize)");

        Ok(Self {
            handle,
            last_status: ffi::PAM_SUCCESS as c_int,
            _conv: conv,
            _creds: creds,
        })
    }
}

impl Drop for PamSession {
    fn drop(&mut self) {
        if self.handle.is_null() {
            return;
        }
        // SAFETY: handle is valid and we have exclusive ownership.
        unsafe {
            ffi::pam_close_session(self.handle, 0);
            ffi::pam_setcred(self.handle, ffi::PAM_DELETE_CRED as c_int);
            ffi::pam_end(self.handle, self.last_status);
        }
        self.handle = ptr::null_mut();
    }
}
