//! PAM authentication and session management.
//!
//! FFI bindings are generated by bindgen from `src/pam_appl.h` (which is the
//! actual Linux-PAM application header). The `ffi` module re-exports everything
//! generated into `$OUT_DIR/pam_appl.rs`.
//!
//! Lifecycle performed by [`PamSession::open`]:
//!   `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
//!   `pam_setcred(ESTABLISH)` → `pam_open_session`
//!
//! [`Drop`] runs:
//!   `pam_close_session` → `pam_setcred(DELETE)` → `pam_end`
//!

// pam_limits    | Applies resource limits (ulimits) from /etc/security/limits.conf
// pam_mkhomedir | Creates home directory on first login if it doesn't exist
// pam_unix      | Core Unix auth — checks passwords against /etc/shadow
// pam_localuser | Succeeds only if user exists in local /etc/passwd
// pam_exec      | Runs an arbitrary external command during auth


#![allow(non_upper_case_globals)]

use std::ffi::*;
use std::mem::{MaybeUninit, size_of};
use std::net::SocketAddr;
use std::ptr::{self, NonNull};

mod ffi {
    #![allow(unused)]
    #![allow(non_camel_case_types)]

    include!(concat!(env!("OUT_DIR"), "/pam_appl.rs"));
}

// ── Conversation callback ─────────────────────────────────────────────────────

struct Credentials {
    username: CString,
    password: CString,
}

/// PAM conversation function.
///
/// Responds with the password for `PAM_PROMPT_ECHO_OFF` prompts and the
/// username for `PAM_PROMPT_ECHO_ON` prompts.
///
/// Response buffer and strings are allocated with `libc::malloc` so that the PAM
/// library can `free()` them with its own allocator.
unsafe extern "C" fn conversation(
    num_msg: c_int,
    msg: *mut *const ffi::pam_message,
    resp: *mut *mut ffi::pam_response,
    appdata_ptr: *mut c_void,
) -> c_int {
    let Ok(num_msg) = num_msg.try_into() else {
        log::debug!("Invalid num_msg {num_msg}");
        return ffi::PAM_CONV_ERR as c_int;
    };

    // SAFETY: this function is only called in `PamSession::authenticate` which always
    // sets the `appdata_ptr` to a pointer to a value of type `Credentials`
    let creds = unsafe { &*appdata_ptr.cast::<Credentials>() };

    // SAFETY: in theory in `msg` we have exclusive access to an array
    // of references to initialized `pam_message` items
    let msg = unsafe { std::slice::from_raw_parts_mut(msg as *mut &ffi::pam_message, num_msg) };

    // SAFETY: todo
    let Some(responses) = (unsafe { malloc::<ffi::pam_response>(num_msg) }) else {
        log::warn!("malloc failed for {num_msg} responses");
        return ffi::PAM_BUF_ERR.cast_signed();
    };

    for (r, m) in responses.iter_mut().zip(msg) {
        let msg = (!m.msg.is_null())
            // SAFETY: PAM guarantees msg is a valid null-terminated string when non-null
            .then(|| unsafe { CStr::from_ptr(m.msg) })
            .unwrap_or(c"");

        match m.msg_style.cast_unsigned() {
            ffi::PAM_PROMPT_ECHO_OFF => log::debug!("Prompt (hidden): {msg:?}"),
            ffi::PAM_PROMPT_ECHO_ON => log::debug!("Prompt (visible): {msg:?}"),
            ffi::PAM_ERROR_MSG => log::debug!("Error message: {msg:?}"),
            ffi::PAM_TEXT_INFO => log::debug!("Info message: {msg:?}"),
            style => log::debug!("Unknown msg_style {style}: {msg:?}"),
        };

        let Some(resp) = (match m.msg_style.cast_unsigned() {
            ffi::PAM_PROMPT_ECHO_OFF => {
                // SAFETY: todo
                unsafe { malloc_cstr(&creds.password) }.map(|s| s.as_mut_ptr())
            }
            ffi::PAM_PROMPT_ECHO_ON => {
                // SAFETY: todo
                unsafe { malloc_cstr(&creds.username) }.map(|s| s.as_mut_ptr())
            }
            _ => Some(std::ptr::null_mut()),
        }) else {
            log::warn!("malloc_cstr failed");
            return ffi::PAM_BUF_ERR.cast_signed();
        };
        r.write(ffi::pam_response {
            resp,
            resp_retcode: 0,
        });
    }
    // SAFETY: the PAM library guarantees that resp is a pointer to a pam_response
    unsafe { *resp = responses.as_mut_ptr() as *mut _ };
    ffi::PAM_SUCCESS as c_int
}

/// An open PAM session for an authenticated user.
///
/// Created via [`PamSession::open`]. Dropping this value closes the session
/// and ends the PAM transaction.
pub struct PamSession {
    handle: *mut ffi::pam_handle_t,
    status: u32,
    // Both fields below must outlive `handle`: Linux-PAM stores a pointer to
    // `conv` internally, and `conv.appdata_ptr` points into `creds`.
    conv: Box<ffi::pam_conv>,
    creds: Box<Credentials>,
}

// SAFETY: the PAM handle is owned exclusively by this struct; we never share
// it across threads and all access is through exclusive ownership.
unsafe impl Send for PamSession {}

macro_rules! pam {
    ($self:expr, $fn:expr, $($param:expr),* $(,)?) => {{
        let res = $fn($self.handle, $($param),*);
        $self.result(stringify!($fn), res)
    }}
}

impl PamSession {
    fn null(username: &str, password: &str) -> anyhow::Result<Self> {
        let creds = Box::new(Credentials {
            username: CString::new(username)?,
            password: CString::new(password)?,
        });

        let conv = Box::new(ffi::pam_conv {
            conv: Some(conversation),
            appdata_ptr: &*creds as *const Credentials as *mut c_void,
        });

        Ok(Self {
            handle: std::ptr::null_mut(),
            status: ffi::PAM_SUCCESS,
            conv,
            creds,
        })
    }

    fn status_str(&self) -> &'static str {
        // SAFETY: todo
        let ptr = unsafe { ffi::pam_strerror(self.handle, self.status.cast_signed()) };
        if ptr.is_null() {
            return "* null *";
        }
        // SAFETY: if the pointer returned by pam_strerror is not null then it's
        // guaranteed to point to a null-terminated byte string
        let str = unsafe { CStr::from_ptr(ptr) };

        str.to_str().unwrap_or("* invalid *")
    }

    fn result(&mut self, step: &str, result: c_int) -> anyhow::Result<()> {
        self.status = result.cast_unsigned();
        log::debug!("{step}: {}", self.status_str());
        anyhow::ensure!(self.status == ffi::PAM_SUCCESS, self.status_str());
        Ok(())
    }

    /// Starts a PAM session with the "ssh-server" service
    fn start(&mut self) -> anyhow::Result<()> {
        // SAFETY:
        // - `service_name` is a null-terminated byte string
        // - `username` is a null-terminated byte string
        let res = unsafe {
            ffi::pam_start(
                c"ssh-server".as_ptr(),
                self.creds.username.as_ptr(),
                &*self.conv,
                &mut self.handle,
            )
        };
        self.result("ffi::pam_start", res)
    }

    /// Sets a PAM item that is expected to be a C string.
    ///
    /// # Safety
    ///
    /// The selected `item` must be one that Linux-PAM expects to be a C string (e.g. `PAM_AUTHTOK` or `PAM_RHOST`).
    unsafe fn set_cstr_item(&mut self, item: u32, value: impl Into<Vec<u8>>) -> anyhow::Result<()> {
        let str = CString::new(value)?;
        // SAFETY: todo
        unsafe {
            pam!(
                self,
                ffi::pam_set_item,
                item.cast_signed(),
                str.as_ptr() as *const _
            )
        }
    }

    /// Authenticate `username`/`password` against the `"ssh-server"` PAM service
    /// and open a session.
    ///
    /// Runs `pam_start` → `pam_authenticate` → `pam_acct_mgmt` →
    /// `pam_setcred(ESTABLISH)` → `pam_open_session`.
    /// Dropping the returned value closes the session via `pam_close_session`,
    /// `pam_setcred(DELETE)`, and `pam_end`.
    pub fn open(username: &str, password: &str, host: SocketAddr) -> anyhow::Result<Self> {
        let mut session = Self::null(username, password)?;
        session.start()?;
        unsafe extern "C" fn nodelay(_: c_int, _: c_uint, _: *const c_void) {}
        // SAFETY: todo
        unsafe {
            pam!(
                session,
                ffi::pam_set_item,
                ffi::PAM_FAIL_DELAY.cast_signed(),
                nodelay as *const _
            )
        }?;
        // SAFETY: todo
        unsafe { session.set_cstr_item(ffi::PAM_AUTHTOK, password) }?;
        // SAFETY: todo
        unsafe { session.set_cstr_item(ffi::PAM_RHOST, username) }?;
        // SAFETY: todo
        unsafe { session.set_cstr_item(ffi::PAM_RHOST, host.to_string()) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_authenticate, 0) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_acct_mgmt, 0) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_setcred, ffi::PAM_ESTABLISH_CRED as c_int) }?;
        // SAFETY: todo
        unsafe { pam!(session, ffi::pam_open_session, 0) }?;
        Ok(session)
    }
}

impl Drop for PamSession {
    fn drop(&mut self) {
        if self.handle.is_null() {
            return;
        }
        // SAFETY: handle is valid and we have exclusive ownership.
        unsafe {
            ffi::pam_close_session(self.handle, 0);
            ffi::pam_setcred(self.handle, ffi::PAM_DELETE_CRED as c_int);
            ffi::pam_end(self.handle, self.status.cast_signed());
        }
        self.handle = ptr::null_mut();
    }
}

/// Utility function to allocate a slice with [`libc::malloc`]
///
/// # Safety
///
/// Same as [`libc::malloc`]
unsafe fn malloc<T>(len: usize) -> Option<&'static mut [MaybeUninit<T>]> {
    let size = len * size_of::<T>();
    // SAFETY: caller must ensure the safety requirements of malloc
    let ptr = unsafe { libc::malloc(size) };
    let ptr = NonNull::new(ptr as *mut MaybeUninit<T>)?;
    // SAFETY: given that the pointer is not null, malloc didn't fail and thus
    // we have gained exclusive access to an unitialized slice of len T items
    Some(unsafe { std::slice::from_raw_parts_mut(ptr.as_ptr(), len) })
}

/// Utility function to allocate a C null-terminated string with [`libc::malloc`]
///
/// # Safety
///
/// Same as [`libc::malloc`]
unsafe fn malloc_cstr(str: &CStr) -> Option<&'static mut [i8]> {
    fn cast(i: &[u8]) -> &[i8] {
        // SAFETY: u8 and i8 have the same binary representation
        unsafe { std::slice::from_raw_parts(i.as_ptr() as *const _, i.len()) }
    }
    let str = cast(str.to_bytes_with_nul());
    // SAFETY: caller must ensure the safety requirements of malloc
    let slice = unsafe { malloc(str.len()) }?;
    Some(slice.write_copy_of_slice(str))
}
